CREATE DATABASE IF NOT EXISTS cinema;

USE cinema;

-- DROP TABLE IF EXISTS `MOVIE`;

CREATE TABLE IF NOT EXISTS `MOVIE` (
	`MOVIE_ID`	INT	NOT NULL AUTO_INCREMENT COMMENT '영화ID',
	`TITLE`	VARCHAR(100)	NULL	COMMENT '영화 제목',
	`GRADE_CD`	VARCHAR(10)	NULL	COMMENT '영상물 등급 [ENUM]',
	`RLSE_DATE`	DATE	NULL	COMMENT '개봉일',
	`THUMB_IMG`	VARCHAR(200)	NULL	COMMENT '썸네일 이미지',
	`RUN_TIME`	INT	NULL	COMMENT '러닝 타임(분)',
	`GENRE_ID`	VARCHAR(20)	NOT NULL	COMMENT '장르ID',
	`REG_USER_ID`	VARCHAR(20)	NULL	COMMENT '작성자',
	`REG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '작성일',
	`CHG_USER_ID`	VARCHAR(20)	NULL	COMMENT '수정자',
	`CHG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일',
	PRIMARY KEY (`MOVIE_ID`)
);

-- DROP TABLE IF EXISTS `GENRE`;

CREATE TABLE IF NOT EXISTS `GENRE` (
	`GENRE_ID`	INT	NOT NULL AUTO_INCREMENT COMMENT '장르ID',
	`GENRE_NM`	VARCHAR(100)	NULL	COMMENT '장르명',
	`REG_USER_ID`	VARCHAR(20)	NULL	COMMENT '작성자',
	`REG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '작성일',
	`CHG_USER_ID`	VARCHAR(20)	NULL	COMMENT '수정자',
	`CHG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일',
	PRIMARY KEY (`GENRE_ID`)
);

-- DROP TABLE IF EXISTS `BOX`;

CREATE TABLE IF NOT EXISTS `BOX` (
	`BOX_ID`	INT	NOT NULL AUTO_INCREMENT COMMENT '상영관ID',
	`BOX_NM`	VARCHAR(100)	NULL	COMMENT '상영관명',
	`LOCATION`	VARCHAR(100)	NULL	COMMENT '위치',
	`REG_USER_ID`	VARCHAR(20)	NULL	COMMENT '작성자',
	`REG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '작성일',
	`CHG_USER_ID`	VARCHAR(20)	NULL	COMMENT '수정자',
	`CHG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일',
	PRIMARY KEY (`BOX_ID`)
);

-- DROP TABLE IF EXISTS `TIMETABLE`;

CREATE TABLE IF NOT EXISTS `TIMETABLE` (
	`TIME_ID`	INT	NOT NULL AUTO_INCREMENT COMMENT '상영시간표ID',
	`MOVIE_ID`	VARCHAR(20)	NOT NULL	COMMENT '영화ID',
	`BOX_ID`	INT	NOT NULL	COMMENT '상영관ID',
	`START_TIME`	TIME	NULL	COMMENT '상영시작시각',
	`END_TIME`	TIME	NULL	COMMENT '상영종료시각',
	`REG_USER_ID`	VARCHAR(20)	NULL	COMMENT '작성자',
	`REG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '작성일',
	`CHG_USER_ID`	VARCHAR(20)	NULL	COMMENT '수정자',
	`CHG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일',
	PRIMARY KEY (`TIME_ID`)
);

-- DROP TABLE IF EXISTS `SEAT_ID`;

CREATE TABLE IF NOT EXISTS `SEAT_ID` (
	`SEAT_ID`	INT	NOT NULL AUTO_INCREMENT COMMENT '좌석ID',
	`SEAT_TYPE_CD`	VARCHAR(20)	NULL	COMMENT '좌석유형 [ENUM]',
	`SEAT_NM`	VARCHAR(20)	NULL	COMMENT '좌석명',
	`REG_USER_ID`	VARCHAR(20)	NULL	COMMENT '작성자',
	`REG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '작성일',
	`CHG_USER_ID`	VARCHAR(20)	NULL	COMMENT '수정자',
	`CHG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일',
	PRIMARY KEY (`SEAT_ID`)
);

-- DROP TABLE IF EXISTS `USER`;

CREATE TABLE IF NOT EXISTS `USER` (
	`USER_ID`	INT	NOT NULL AUTO_INCREMENT COMMENT '회원ID',
	`USER_NM`	VARCHAR(20)	NULL	COMMENT '회원명',
	`BIRTH_DATE`	DATE	NULL	COMMENT '생년월일',
	`REG_USER_ID`	VARCHAR(20)	NULL	COMMENT '작성자',
	`REG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '작성일',
	`CHG_USER_ID`	VARCHAR(20)	NULL	COMMENT '수정자',
	`CHG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일',
	PRIMARY KEY (`USER_ID`)
);

-- DROP TABLE IF EXISTS `TICKET`;

CREATE TABLE IF NOT EXISTS `TICKET` (
	`TICKET_ID`	INT	NOT NULL AUTO_INCREMENT COMMENT '예매ID',
	`USER_ID`	VARCHAR(20)	NOT NULL	COMMENT '회원ID',
	`SEAT_ID`	VARCHAR(20)	NOT NULL	COMMENT '좌석ID',
	`TIME_ID`	VARCHAR(20)	NOT NULL	COMMENT '상영시간표ID',
	`REG_USER_ID`	VARCHAR(20)	NULL	COMMENT '작성자',
	`REG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '작성일',
	`CHG_USER_ID`	VARCHAR(20)	NULL	COMMENT '수정자',
	`CHG_DTTM`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일',
	PRIMARY KEY (`TICKET_ID`)
);


