CREATE DATABASE IF NOT EXISTS cinema;

USE cinema;

DROP TABLE IF EXISTS `movie`;

CREATE TABLE `movie` (
	`movie_id` INT NOT NULL AUTO_INCREMENT COMMENT '영화ID',
	`title` VARCHAR(100) NULL COMMENT '영화 제목',
	`grade_cd` VARCHAR(10) NULL COMMENT '영상물 등급',
	`rlse_date` DATE NULL COMMENT '개봉일',
	`thumb_img` VARCHAR(200) NULL COMMENT '썸네일 이미지',
	`run_time` INT NULL COMMENT '러닝 타임(분)',
	`genre_id` VARCHAR(20) NOT NULL COMMENT '장르ID',
	`reg_user_id` VARCHAR(20) NULL COMMENT '작성자',
	`reg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
	`chg_user_id` VARCHAR(20) NULL COMMENT '수정자',
	`chg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일',
	PRIMARY KEY (`movie_id`)
);

DROP TABLE IF EXISTS `genre`;

CREATE TABLE `genre` (
	`genre_id` INT NOT NULL AUTO_INCREMENT COMMENT '장르ID',
	`genre_nm` VARCHAR(100) NULL COMMENT '장르명',
	`reg_user_id` VARCHAR(20) NULL COMMENT '작성자',
	`reg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
	`chg_user_id` VARCHAR(20) NULL COMMENT '수정자',
	`chg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일',
	PRIMARY KEY (`genre_id`)
);

DROP TABLE IF EXISTS `box`;

CREATE TABLE `box` (
	`box_id` INT NOT NULL AUTO_INCREMENT COMMENT '상영관ID',
	`box_nm` VARCHAR(100) NULL COMMENT '상영관명',
	`location` VARCHAR(100) NULL COMMENT '위치',
	`reg_user_id` VARCHAR(20) NULL COMMENT '작성자',
	`reg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
	`chg_user_id` VARCHAR(20) NULL COMMENT '수정자',
	`chg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일',
	PRIMARY KEY (`box_id`)
);

DROP TABLE IF EXISTS `timetable`;

CREATE TABLE `timetable` (
	`time_id` INT NOT NULL AUTO_INCREMENT COMMENT '상영시간표ID',
	`movie_id` VARCHAR(20) NOT NULL COMMENT '영화ID',
	`box_id` INT NOT NULL COMMENT '상영관ID',
	`show_date` DATE NOT NULL COMMENT '상영일자',
	`start_time` TIME NOT NULL COMMENT '상영시작시각',
	`end_time` TIME NOT NULL COMMENT '상영종료시각',
	`reg_user_id` VARCHAR(20) NULL COMMENT '작성자',
	`reg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
	`chg_user_id` VARCHAR(20) NULL COMMENT '수정자',
	`chg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일',
	PRIMARY KEY (`time_id`)
);

DROP TABLE IF EXISTS `seat`;

CREATE TABLE `seat` (
	`seat_id` INT NOT NULL AUTO_INCREMENT COMMENT '좌석ID',
	`seat_type_cd` VARCHAR(20) NULL COMMENT '좌석유형',
	`seat_nm` VARCHAR(20) NULL COMMENT '좌석명',
	`reg_user_id` VARCHAR(20) NULL COMMENT '작성자',
	`reg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
	`chg_user_id` VARCHAR(20) NULL COMMENT '수정자',
	`chg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일',
	PRIMARY KEY (`seat_id`)
);

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
	`user_id` INT NOT NULL AUTO_INCREMENT COMMENT '회원ID',
	`user_nm` VARCHAR(20) NULL COMMENT '회원명',
	`birth_date` DATE NULL COMMENT '생년월일',
	`reg_user_id` VARCHAR(20) NULL COMMENT '작성자',
	`reg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
	`chg_user_id` VARCHAR(20) NULL COMMENT '수정자',
	`chg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일',
	PRIMARY KEY (`user_id`)
);

DROP TABLE IF EXISTS `ticket`;

CREATE TABLE `ticket` (
	`ticket_id` INT NOT NULL AUTO_INCREMENT COMMENT '예매ID',
	`user_id` VARCHAR(20) NOT NULL COMMENT '회원ID',
	`seat_id` VARCHAR(20) NOT NULL COMMENT '좌석ID',
	`time_id` VARCHAR(20) NOT NULL COMMENT '상영시간표ID',
	`reg_user_id` VARCHAR(20) NULL COMMENT '작성자',
	`reg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
	`chg_user_id` VARCHAR(20) NULL COMMENT '수정자',
	`chg_dttm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일',
	PRIMARY KEY (`ticket_id`)
);


