spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cinema?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: cinema_user
    password: cinema_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # Hibernate가 DDL을 생성하지 않도록 설정
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
#      host: redis-container
      port: 6379
#      password: cinema_password
      serializer: jackson
  cache:
    type: redis
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    serialization:
      fail-on-empty-beans: false

# 상영시간표별 최대 예매 가능 수
max-count:
  theater-bookable: 5

logging:
  level:
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
